/// <reference types="@cloudflare/workers-types" />

// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import { default as handler } from "./.open-next/worker.js";
import { setRuntimeCloudflareEnv } from "./src/lib/db";
import { refreshMarketData } from "./src/lib/marketRepo";
import { refreshForecastSnapshot } from "./src/lib/forecastSnapshot";

const FORECAST_LIST_CACHE_SECONDS = 60;
const FORECAST_CACHE_KEY_VERSION = "r2-v2";

type RateLimitBinding = {
  limit: (options: { key: string }) => Promise<{ success: boolean }>;
};

type AppEnv = CloudflareEnv & {
  FORECAST_SUBMISSIONS_LIMITER?: RateLimitBinding;
};

type CloudflareCacheStorage = CacheStorage & {
  default: Cache;
};

function isForecastSubmissionRequest(request: Request): boolean {
  const url = new URL(request.url);
  return request.method === "POST" && url.pathname === "/api/forecasts";
}

function isCacheableForecastRequest(request: Request): boolean {
  const url = new URL(request.url);
  return (
    request.method === "GET" &&
    (url.pathname === "/api/forecast-snapshot/manifest" ||
      url.pathname.startsWith("/api/forecast-snapshot/chunks/"))
  );
}

function getForecastCacheControl(request: Request, response: Response): string {
  const url = new URL(request.url);

  if (url.pathname.startsWith("/api/forecast-snapshot/chunks/")) {
    return response.headers.get("Cache-Control") ?? "public, max-age=31536000, immutable";
  }

  return `public, max-age=${FORECAST_LIST_CACHE_SECONDS}`;
}

function withForecastCacheHeaders(request: Request, response: Response, status: "HIT" | "MISS"): Response {
  const cachedResponse = new Response(response.body, response);
  cachedResponse.headers.set("Cache-Control", getForecastCacheControl(request, response));
  cachedResponse.headers.set("X-Forecast-Cache", status);
  return cachedResponse;
}

function getClientIp(request: Request): string {
  return (
    request.headers.get("CF-Connecting-IP") ??
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
    "unknown"
  );
}

async function rateLimitForecastSubmission(request: Request, env: AppEnv): Promise<Response | null> {
  if (!isForecastSubmissionRequest(request) || !env.FORECAST_SUBMISSIONS_LIMITER) {
    return null;
  }

  const { success } = await env.FORECAST_SUBMISSIONS_LIMITER.limit({
    key: `forecast-submission:${getClientIp(request)}`
  });

  if (success) {
    return null;
  }

  return Response.json(
    { message: "Too many forecast submissions. Try again in a minute." },
    {
      status: 429,
      headers: {
        "Cache-Control": "no-store",
        "Retry-After": "60"
      }
    }
  );
}

async function handleFetch(request: Request, env: AppEnv, ctx: ExecutionContext): Promise<Response> {
  setRuntimeCloudflareEnv(env);

  const rateLimitedResponse = await rateLimitForecastSubmission(request, env);

  if (rateLimitedResponse) {
    return rateLimitedResponse;
  }

  if (!isCacheableForecastRequest(request)) {
    const response = await handler.fetch(request, env, ctx);

    if (new URL(request.url).pathname === "/api/forecasts") {
      const forecastResponse = new Response(response.body, response);
      forecastResponse.headers.set(
        "Cache-Control",
        response.headers.get("X-Forecast-Source") === "snapshot"
          ? `public, max-age=${FORECAST_LIST_CACHE_SECONDS}`
          : "no-store"
      );
      return forecastResponse;
    }

    return response;
  }

  const cache = (caches as CloudflareCacheStorage).default;
  const cacheKeyUrl = new URL(request.url);
  cacheKeyUrl.searchParams.set("__forecast_cache", FORECAST_CACHE_KEY_VERSION);
  const cacheKey = new Request(cacheKeyUrl.toString(), request);
  const cached = await cache.match(cacheKey);

  if (cached) {
    return withForecastCacheHeaders(request, cached, "HIT");
  }

  const response = await handler.fetch(request, env, ctx);

  if (response.ok) {
    const responseToCache = withForecastCacheHeaders(request, response.clone(), "MISS");
    ctx.waitUntil(cache.put(cacheKey, responseToCache.clone()));
    return responseToCache;
  }

  return response;
}

export default {
  fetch: handleFetch,

  async scheduled(controller, env, ctx) {
    setRuntimeCloudflareEnv(env);
    const cron = controller.cron;

    if (!cron || cron === "0 */2 * * *") {
      ctx.waitUntil(refreshMarketData());
    }

    if (!cron || cron === "* * * * *") {
      ctx.waitUntil(refreshForecastSnapshot());
    }
  }
} satisfies ExportedHandler<AppEnv>;

// Required if OpenNext cache durable objects are enabled later.
// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
